config/routes.rb
Ftweb::Application.routes.draw do

  resources :units

  get "sessions/new"

  resources :users do
    resources :recipes do
      collection do
        get "clippings"
      end
    end
  end

  resources :tags

  resources :recipes do
    resources :supplies
    resources :tags
    member do
      put "clip"
      get "clip" #for debug purposes mostly
      delete 'clip', action:'unclip'
      get 'unclip'
      delete 'unclip'
    end
  end

  resources :ingredients
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions

  root :to => 'recipes#index'

  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User', :inverse_of=>:created_recipes
  has_many :supplies, :dependent => :destroy
  has_many :ingredients, :through => :supplies
  has_and_belongs_to_many :tags
  has_many :recipe_bookmarks
  has_many :clippers, :through=>:recipe_bookmarks, :source=>:user, :class_name => "User"

  scope :recent, order('created_at desc')
  scope :by_user, lambda{|user| where(:creator_id=>user.id)}

  accepts_nested_attributes_for :supplies, :allow_destroy => true, :reject_if=>:reject_supply?

  #attr_accessible :ingredients_box
  #virtual_attribute :ingredients_box

  def reject_supply?(attributed)
    attributed['name'].blank? and attributed['ingredient_id'].blank?
  end

  def clipped_by? (user)
    clippers.exists?(id:user.id)
  end

  validates :name, :presence=>true
  validates :cook_time, :prep_time, :numericality => { :only_integer => false }

  searchable do
    text :name, :boost=>10
    text :description, :boost=>2
    text :steps
    text :ingredients, :boost=>5 do
      ingredients.map(&:name)
    end
    text :tags do
      tags.map(&:name)
    end
  end

  scope :search
  def self.search(text)
    s=Recipe.solr_search_ids do
      keywords text
    end
    Recipe.where(:id=>s) #this returns an ActiveRecord::Relation instead of a vanilla array, which is expected by has_scope.
  end

  scope :tag
  def self.tag(name)
    Recipe.joins(:tags).where("upper(tags.name)=?",name.humanize.upcase)
  end

  attr_writer :tag_names
  after_save :assign_tags

  def tag_names
    @tag_names || tags.map(&:name).join(', ')
  end

  def total_time
    self.cook_time+self.prep_time
  end

  def remove_bookmark_for_user (user)
    clippers.delete user
  end


  def ingredients_box=(text)
    @ingredients_box = text
  end

  def ingredients_box
    @ingredients_box || ""
  end

  def cook_time_minutes
    (cook_time || 0)/1.minute
  end

  def cook_time_minutes=(time)
    self.cook_time=time.to_f.minutes
  end

  def prep_time_minutes
    (prep_time || 0)/1.minute
  end

  def prep_time_minutes=(time)
    self.prep_time=time.to_f.minutes
  end



  #private
  def assign_tags
    if @tag_names
      self.tags = @tag_names.split(/,\s*/).map do |name|
        Tag.find_or_create_by_name(name)
      end
    end
  end

  after_save :assign_supplies
  def assign_supplies
    supply_a = []
    ingredients_box.split('\n').each do |line_item|
      supply_a << Supply.parse_line_item(line_item)
    end
    supplies = supply_a
  end

  #attr_writer :ingredients_box



end

app/controllers/recipes_controller.rb
class RecipesController < InheritedResources::Base
  respond_to :html, :xml, :json
  optional_belongs_to :user

  has_scope :search, :tag

  before_filter :require_login, only: [:create, :new, :edit]
  # GET /recipes
  # GET /recipes.json
  def index
    if params[:user_id] then
      @recipes=User.find(params[:user_id]).created_recipes
      respond_with do |format|
        format.html { @recipes=RecipeDecorator.decorate @recipes }
        format.json { render json: RecipeJsonDecorator.decorate(@recipes) }
      end
    else
      @featured ||= RecipeDecorator.decorate Recipe.recent.limit(2) unless params[:search]
      index! do |format|
        format.html { @recipes=RecipeDecorator.decorate @recipes }
        format.json { render json: RecipeJsonDecorator.decorate(@recipes) }
      end
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    show! do |format|
      format.html { @recipe = RecipeDecorator.decorate(@recipe) }
      format.json { render json: RecipeJsonDecorator.decorate(@recipe) }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
  #  @recipe = Recipe.new
  #
    new! do |format|
      # format.html # new.html.erb
      # format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
  #  @recipe = Recipe.find(params[:id])
    edit!
  end

  # POST /recipes
  # POST /recipes.json
  def create
  #  @recipe = Recipe.new(params[:recipe])
  #
    create! do |success, failure|
  #    if @recipe.save # Not needed!
  #      success.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
  #      success.json { render json: @recipe, status: :created, location: @recipe }
  #    else
  #      failure.html { render action: "new" }
  #      failure.json { render json: @recipe.errors, status: :unprocessable_entity }
  #    end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
  #  @recipe = Recipe.find(params[:id])
  #
    update! do |success, failure|
  #    success.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
  #    success.json { head :ok }
  #    failure.html { render action: "edit" }
  #    failure.json { render json: @recipe.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
  #  @recipe = Recipe.find(params[:id])
  #  @recipe.destroy
  #
    destroy! do |format|
  #    format.html { redirect_to recipes_url }
  #    format.json { head :ok }
    end
  end
  
  # PUT /recipes/1/clip[.json]
  def clip
    @recipe=Recipe.find(params[:id])
    respond_with do |format|
      begin
        current_user.clippings << @recipe
        format.html {redirect_to :back, notice: 'Recipe was successfully added.'}
        format.json do
           render json: {
            links: [
              {rel: 'self', href: recipe_url(@recipe)},
              {rel: 'added_to', href: clippings_user_recipes_url(current_user)}
              ], 
            notice:'Recipe was successfully added.', 
            changed:true}, # TODO dry this up
           status: :ok
        end
      rescue ActiveRecord::RecordInvalid => invalid
        if invalid.record.errors[:recipe_id] then
          format.html { redirect_to :back, notice: 'Recipe has already been clipped' }
          format.json do
             render json: {
              links: [
                {rel: 'self', href: recipe_url(@recipe)},
                {rel: 'added_to', href: clippings_user_recipes_url(current_user)}
                ], 
              notice:'Recipe has already been clipped.', 
              changed:false}, # TODO dry this up
             status: :ok
          end
        else
          raise invalid
        end
      end
    end
  end
  
  # DELETE /recipes/1/clip[.json]
  # GET /recipes/1/unclip[.json]
  def unclip
    @recipe=Recipe.find(params[:id])
    @recipe.remove_bookmark_for_user current_user
    respond_with do |format|
      format.html {redirect_to :back, notice: "Recipe removed from your clipped recipes"}
      format.json {head :ok}
    end
  end
  
  # GET /users/1/recipes/clippings[.json]
  def clippings
    @recipes = User.find(params[:user_id]).clippings
    respond_with do |format|
      format.html do
        @recipes=RecipeDecorator.decorate @recipes 
        render 'index'
      end
      format.json { render json: RecipeJsonDecorator.decorate(@recipes) }
    end
  end

  private
  def not_authenticated
    redirect_to login_url, alert: "You must first log in to view this page."
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_featured.html.haml
.featured
  %h2= link_to recipe.name, recipe
  .description
    :markdown
      #{h recipe.description}
  .tags!= recipe.tag_links
  .clip
    - if !recipe.clipped?
      = link_to 'Clip this recipe for later!', clip_recipe_path(recipe), :method=>:put
    -else
      = link_to 'Remove from clipped recipes', clip_recipe_path(recipe), :method=>:delete

app/views/recipes/_featured_list.html.haml
#featured-recipe-list
  %h2 Featured
  - for recipe in @featured
    =render :partial=>'featured', :locals=>{:recipe=>recipe}

app/views/recipes/_form.html.haml
= form_for(@recipe) do |f|
  - if @recipe.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@recipe.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @recipe.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    = f.label "Recipe Name:", for: :name
    %br
    = f.text_field :name
  .field
    = f.label :cook_time, for: :cook_time_minutes
    = f.number_field :cook_time_minutes
    minutes
  .field
    = f.label :prep_time, for: :prep_time_minutes
    = f.number_field :prep_time_minutes
    minutes
    
  .field
    = f.label :description
    %br
    = f.text_area :description

  .fields
    = render :partial => "supply_fields", :locals => { :f => f }

  .field
    = f.label :steps
    %br
    = f.text_area :steps
  .field
    = f.label :tag_names
    %br
    = f.text_field :tag_names
    /= render 'supply_fields'
    /= f.fields_for :supplies
    /= f.link_to_add "Add another ingredient", :supplies
  
  .actions
    = f.submit

app/views/recipes/_line_item.html.haml
%h3= link_to recipe.name, recipe_path(recipe)
.description
  :markdown
    #{h recipe.description[0..100]}...

app/views/recipes/_listing.html.haml
%div{ :class => [cycle(:odd, :even),"listing",recipe.clipped?()? 'clipped' : 'unclipped'] }
  %h3= link_to recipe.name, recipe
  %dl.cook_times
    %dt Cook Time
    %dd= recipe.cook_time_dhms
    %dt Prep Time
    %dd= recipe.prep_time_dhms
  .description
    :markdown
      #{h recipe.description}
  .tags!= recipe.tag_links
  .clip
    - if !recipe.clipped?
      = link_to 'Clip this recipe for later!', clip_recipe_path(recipe), :method=>:put
    -else
      = link_to 'Remove from clipped recipes', clip_recipe_path(recipe), :method=>:delete

app/views/recipes/_recipe_detail_list.html.haml
%table
  %thead
    %tr
      %th= Recipe.human_attribute_name :name
      %th= Recipe.human_attribute_name :cook_time
      %th= Recipe.human_attribute_name :prep_time
      %th= Recipe.human_attribute_name :description
      %th= Recipe.human_attribute_name :steps
      %th= 'Tags'
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for recipe in @recipes
      %tr{ :class => cycle(:odd, :even) }
        %td= recipe.name
        %td= recipe.cook_time_dhms
        %td= recipe.prep_time_dhms
        %td= recipe.description
        %td= recipe.steps
        %td= recipe.tag_names
        %td.action= link_to t('show'), recipe
        %td.action= link_to t('edit'), edit_recipe_path(recipe)
        %td.action= link_to t('destroy'), recipe, :confirm => t('are_you_sure'), :method => :delete

app/views/recipes/_recipe_list.html.haml
#recipe-list
  %h2 Results
  - for recipe in @recipes
    =render :partial=>'listing', :locals=>{:recipe=>recipe}

app/views/recipes/_supply_fields.html.haml
.fields
  /.field
  /  = f.label :amount_tokens
  /  %br
  /  = f.text_field :amount_tokens
  /.field
  /  = f.label :unit
  /  %br
  /  = f.text_field :unit
  .field
    = f.label :ingredients, :for => :ingredients_box
    = f.text_area :ingredients_box
  /.field
  /  = f.label :name
  /  %br
  /  = f.text_field :name
  /= f.link_to_remove "Remove This Ingredient"

app/views/recipes/_unit_fields.html.haml
= f.fields_for :amount_token

app/views/recipes/edit.html.haml
%h1 Edit Recipe
%p
  = link_to t('back'), recipes_path
  = link_to t('show'), @recipe
= render 'form'

app/views/recipes/home.html.haml
//%h1= "FoodThink"
//%h3= "WEB"

/ .search{:class => 'search_box'}
/   = form_tag recipes_path(), :method=>:get do
/     = label_tag :search, "Search:"
/     = text_field_tag :search, params["search"]
/     = submit_tag "Search"

- for recipe in @featured
  =render :partial=>'featured', :locals=>{:recipe=>recipe}

= render 'recipe_list'

app/views/recipes/index.html.haml
%h1 Recipes

%p= link_to t('.new_recipe'), new_recipe_path
#recipes
  = render 'featured_list' if @featured
  = render 'recipe_list'

app/views/recipes/new.html.haml
%h1 Create a Recipe
%p= link_to t('back'), recipes_path
= render 'form'

app/views/recipes/show.html.haml
%h1= @recipe.name
.recipe-detail
  %p
    = link_to t('back'), recipes_path
    = link_to t('edit'), edit_recipe_path(@recipe)

  %dl
    %dt= Recipe.human_attribute_name :cook_time
    %dd= @recipe.cook_time_dhms
    %dt= Recipe.human_attribute_name :prep_time
    %dd= @recipe.prep_time_dhms
    %dt= Recipe.human_attribute_name :description
    %dd
      :markdown
        #{h @recipe.description}
    %dt Ingredients
    %dd
      = '(no ingredients)' if @recipe.supplies.empty?
      - if !@recipe.supplies.empty?
        %table.ingredients
          %thead
            %tr
              %th(colspan=2) Amount
              %th Ingredient
          %tbody
            - for supply in @recipe.supplies
              %tr
                %td= supply.amount
                %td= supply.unit
                %td= supply.name
    %dt= Recipe.human_attribute_name :steps
    %dd
      :markdown
        #{h @recipe.steps}
    %dt Tags
    %dd= @recipe.tag_names
    -unless @recipe.creator.nil?
      %dt Creator
      %dd= link_to @recipe.creator.username, user_recipes_path(@recipe.creator)