config/routes.rb
Ftweb::Application.routes.draw do

  resources :units

  get "sessions/new"

  resources :users do
    resources :recipes do
      collection do
        get "clippings"
      end
    end
  end

  resources :tags

  resources :recipes do
    resources :supplies
    resources :tags
    member do
      put "clip"
      get "clip" #for debug purposes mostly
      delete 'clip', action:'unclip'
      get 'unclip'
      delete 'unclip'
    end
  end

  resources :ingredients
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions

  root :to => 'recipes#index'

  
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  attr_accessible :name, :amount_tokens
  belongs_to :ingredient
  belongs_to :recipe
  belongs_to :unit

  attr_reader :amount_tokens
  
  #validates :unit, :inclusion => { :in => %w(Tablespoons Teaspoons Cups Pints Ounces Fluid\ Ounces Gallons Liters Pinches Dashes),
  #    :message => "%{value} is not a valid unit" }
  
  accepts_nested_attributes_for :ingredient
  
  scope :all_for_recipe, lambda {|recipe_id| where(:recipe_id=>recipe_id)}
  

  before_save :link_ingr_by_name
  def name=(value)
    attribute_will_change!(:name) #not sure if this line is needed
    @name=value
  end
  def name
    return ingredient.name unless ingredient.nil?
    return ''
  end
  
  def link_ingr_by_name
    self.ingredient= Ingredient.find_or_create_by_name(@name)
  end
  
  def as_json(options={})
    {
      :id=>self.ingredient_id,
      :name=>self.ingredient.name,
      :description=>self.ingredient.description,
      :amount=>{:unit=>self.unit, :quantity=>self.amount},
    }
  end

  def amount_tokens=(ids)
    self.amounts = ids.split(',')
  end
  
  def self.parse_line_item(line_item)

    tokens = line_item.match(/^\s*(?<amount>[0-9]*\s[0-9]+\/[0-9]+|[0-9]+\/[0-9]+|[0-9]*\.?[0-9]+)\s+(?<unit>[A-Za-z]+)\s+(?<ingredient>[A-Za-z\s]+)$/)
    supply=Supply.new

    supply.amount = Fractional.to_f(tokens[:amount])
    supply.unit = Unit.find_or_create_by_name(tokens[:unit])
    supply.ingredient = Ingredient.find_or_create_by_name(tokens[:ingredient])
    supply
  end

end

app/controllers/supplies_controller.rb
class SuppliesController < InheritedResources::Base
  belongs_to :recipe
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.haml
= form_for([@supply.recipe, @supply]) do |f|
  - if @supply.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@supply.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @supply.errors.full_messages.each do |msg|
        %li= msg
  .field
    sdfsfs
    label "Field Token"
    = text_field :amount
-#  .field
-#    = f.label :amount
-#    %br
-#    = f.text_field :amount
-#  .field
-#    = f.label :unit
-#    %br
-#    = f.text_field :unit
-#  .field
-#    = f.label :name
-#    %br
-#    = f.text_field :name

  .actions
    = f.submit

app/views/supplies/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), recipe_supplies_path
  = link_to t('show'), recipe_supply_path(@supply.recipe, @supply)
= render 'form'

app/views/supplies/index.html.haml
%h1= t('.title')
%p= link_to t('.new_supply'), new_recipe_supply_path

= render 'application/login_panel'
%table
  %thead
    %tr
      %th= Supply.human_attribute_name :amount
      %th= Supply.human_attribute_name :unit
      %th Name
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for supply in @supplies
      %tr{ :class => cycle(:odd, :even) }
        %td= supply.amount
        %td= supply.unit
        %td= supply.name
        %td.action= link_to t('show'), recipe_supply_path(supply.recipe, supply)
        %td.action= link_to t('edit'), edit_recipe_supply_path(supply.recipe, supply)
        %td.action= link_to t('destroy'), recipe_supply_path(supply.recipe, supply), :confirm => t('are_you_sure'), :method => :delete

app/views/supplies/new.html.haml
%h1= t '.title'
%p= link_to t('back'), supplies_path
= render 'form'

app/views/supplies/show.html.haml
%h1
  Supplies for
  =link_to @supply.recipe.name, recipe_path(@supply.recipe)
%p
  = link_to t('back'), recipe_supplies_path
  = link_to t('edit'), edit_recipe_supply_path(@supply.recipe, @supply)

%dl
  %dt= Supply.human_attribute_name :amount
  %dd= @supply.amount
  %dt= Supply.human_attribute_name :unit
  %dd= @supply.unit
  %dt Name
  %dd= @supply.name