config/routes.rb
Ftweb::Application.routes.draw do

  resources :units

  get "sessions/new"

  resources :users do
    resources :recipes do
      collection do
        get "clippings"
      end
    end
  end

  resources :tags

  resources :recipes do
    resources :supplies
    resources :tags
    member do
      put "clip"
      get "clip" #for debug purposes mostly
      delete 'clip', action:'unclip'
      get 'unclip'
      delete 'unclip'
    end
  end

  resources :ingredients
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions

  root :to => 'recipes#index'

  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :recipes
  validates_uniqueness_of :name
end

app/controllers/tags_controller.rb
class TagsController < InheritedResources::Base
  optional_belongs_to :recipe
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= form_for(@tag) do |f|
  - if @tag.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@tag.errors.count, 'error')} prohibited this user from being saved:"
      %ul
      - @tag.errors.full_messages.each do |msg|
        %li= msg
  
  .field
    = f.label :name
    %br
    = f.text_field :name

  .actions
    = f.submit

app/views/tags/edit.html.haml
%h1= t '.title'
%p
  = link_to t('back'), tags_path
  = link_to t('show'), @tag
= render 'form'

app/views/tags/index.html.haml
%h1= t('.title')
%p= link_to t('.new_tag'), new_tag_path

%table
  %thead
    %tr
      %th= Tag.human_attribute_name :name
      %th{:colspan => 3}= t 'actions'
  
  %tbody
    - for tag in @tags
      %tr{ :class => cycle(:odd, :even) }
        %td= tag.name
        %td.action= link_to t('show'), tag
        %td.action= link_to t('edit'), edit_tag_path(tag)
        %td.action= link_to t('destroy'), tag, :confirm => t('are_you_sure'), :method => :delete

app/views/tags/new.html.haml
%h1= t '.title'
%p= link_to t('back'), tags_path
= render 'form'

app/views/tags/show.html.haml
%h1= t '.title'
%p
  = link_to t('back'), tags_path
  = link_to t('edit'), edit_tag_path(@tag)

%dl
  %dt= Tag.human_attribute_name :name
  %dd= @tag.name