config/routes.rb
Ftweb::Application.routes.draw do

  resources :units

  get "sessions/new"

  resources :users do
    resources :recipes do
      collection do
        get "clippings"
      end
    end
  end

  resources :tags

  resources :recipes do
    resources :supplies
    resources :tags
    member do
      put "clip"
      get "clip" #for debug purposes mostly
      delete 'clip', action:'unclip'
      get 'unclip'
      delete 'unclip'
    end
  end

  resources :ingredients
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions

  root :to => 'recipes#index'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def user_recipes( user=nil )
    user=current_user if user.nil?
    user.created_recipes
  end
  
  def user_clippings( user=nil )
    user=current_user if user.nil?
    user.clippings
  end
  
  def mkd( text )
    BlueCloth.new(text).to_html
  end
  
end

app/views/application/_flash.html.haml
- flash.each do |type, value|
  .flash.div.error{ :class => type.to_s}
    = value 

app/views/application/_header.html.haml
%nav.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      =link_to 'FoodThink', root_path, class: :brand
      =render 'login_form'

app/views/application/_login_form.html.haml
-if current_user
  =link_to 'Logout', logout_path, class: :'navbar_link pull-right'
-else
  =form_tag sessions_path, method: :post, class: :'navbar-form pull-right' do
    .input-append
      = text_field_tag :username, nil, placeholder:"username"
      = password_field_tag :password, nil, placeholder:"password"
      = submit_tag "Log in", class: :btn
      = link_to "Sign up", signup_path, class: :'btn btn-navbar'

app/views/application/_login_panel.html.haml
- if current_user
  = 'Logged in as ' 
  = current_user.username
  = link_to 'Logout', logout_path
-else
  = link_to "Sign up", signup_path
  = 'or'
  = link_to "Log in", login_path

app/views/application/_markdown_help.html.haml
%h3 Formatting
.formatting
  :plain
    <strong>Bold</strong>: *bold* <br />
    <em>Italic</em>: _italic_ <br />
    List: <br />
    * Item 1<br />
    * Item 2<br />
    <br />
    Numbered List:<br />
    1. Item 1<br />
    2. Item 2<br />

app/views/application/_recipe_clippings.html.haml
%dl
  %dt.section My Recipes
  %dd
    %ul
      - for recipe in user_recipes
        %li= render :partial=>"recipes/line_item", :locals=>{:recipe=>recipe}
  %dt.section Favorite Recipes
  %dd
    %ul
      - for recipe in user_clippings
        %li= render :partial=>"recipes/line_item", :locals=>{:recipe=>recipe}
        

app/views/application/_search.html.haml
.search
  = form_tag recipes_path(), method: :get, class: "form-search" do
    = text_field_tag :search, params["search"], placeholder: "Search Recipes", class: "search-query"
    = submit_tag "Search", :class => "btn"

app/views/application/_workbench.html.haml
%dl
  -unless !current_user
    %dt.user.section= current_user.username
    %dd.user
      = current_user.email
      #login_panel= render 'login_panel'
    %dt.section recipe clippings
    %dd= render 'recipe_clippings'
    %dt.section my pantry
    %dd lorem
  -else
    %dt.user.guest.section Welcome, Guest!
    %dd.user.guest= render 'login_panel'